Sofware is controlled via the Containerfile. To change or add packages,
they need to be defined here before build time. Updating already built
images with later versions would only need a rebuild.

Switch to the `Build host` terminal and open the `Containervile` for editing.

To the end of the `+dnf install+` line, add `+vim+` to the list of
packages installed.

[source,bash,run,subs=attributes+]
----
vi Containerfile
----

[source,dockerfile,nocopy]
----
FROM registry.redhat.io/rhel10/rhel-bootc:10.0

ADD etc /etc

RUN dnf install -y httpd vim # <1>
RUN systemctl enable httpd
----
<1> Adding `vim` to this `RUN` line is the only update we need to make to install
additional packages

== Use podman to update the image.

With our changes in the Containerfile, we can re-run the
`+podman build+` command to get an updated image.

[source,bash,run,subs=attributes+]
----
podman build -t builder.{guid}.{domain}:5000/test-bootc .
----

Since the `+RUN+` command to install software happens after the `+ADD+`
command to install config files, notice `+podman+` used the cached layer
rather than rebuilding it. Layer caching and ordering can be a powerful
tool when designing and updating standard operating builds.

== Push the image to the registry

Once the updated image has been built, we can push it to the registry.
Once again, note how only the changed layers need to be added to the
registry.

[source,bash,run,subs=attributes+]
----
podman push builder.{guid}.{domain}:5000/test-bootc
----

In the next step, we’ll look at how to update a running system from the
new image we just pushed to the registry.
